#!/bin/bash

# Function to display information about a subdomain
get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type="$(dig +short -t A "$subdomain.$domain" | awk '{ if ($0 ~ /:/) print "AAAA"; else print "A" }')"
    local destination="$(dig +short "$subdomain.$domain")"

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script
if [ $# -eq 1 ]; then
    # Display information for default subdomains www, lb-01, web-01, and web-02
    domain="$1"
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
elif [ $# -eq 2 ]; then
    # Display information for the specified subdomain
    domain="$1"
    subdomain="$2"
    get_subdomain_info "$domain" "$subdomain"
else
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi

exit 0
