#!/usr/bin/env bash
global
        log /dev/log    local0
	stats socket /run/haproxy/admin.sock mode 660 level admin

defaults

    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend chrisigebs.tech.pem
    bind *:80
    bind *:443 ssl crt /etc/haproxy/certs/chrisigebs.tech.pem
    http-request redirect scheme https  if !{ ssl_fc }
    default_backend chrisigebs.tech.pem

backend chrisigebs.tech.pem
    http-request redirect scheme https if  !{ ssl_fc }
    balance roundrobin
    server 130022-web-01 52.3.246.137:80 check
    server 130022-web-02 3.84.222.135:80 check	
