#!/usr/bin/env bash
global
        log /dev/log    local0
	stats socket /run/haproxy/admin.sock mode 660 level admin

defaults
        log     global
        mode    http
        option  httplog
	timeout connect  10s
	timeout client  30s
	timeout server  30s

frontend th3gr00t-tech-frontend
	bind *:80
	bind *:443 ssl crt /etc/haproxy/certs/chrisigebs.tech.pem
	http-request redirect scheme https code 301 unless { ssl_fc }
	http-request set-header X-Forwarded-Proto https
	default_backend chrisigebs-tech-backend

backend th3gr00t-tech-backend
	balance roundrobin
	server 346671-web-01 52.3.246.137:80 check
	server 346671-web-02 3.84.222.135:80 check
