#!/bin/bash

# Update package list
sudo apt-get update

# Install Nginx with the -y flag to avoid interactive prompts
sudo apt-get -y install nginx

# Create an HTML file with "Hello World!"
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
