#!/usr/bin/env bash
# Configure a custom 404 page for Nginx

# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Set permissions for web directory
chmod -R 755 /var/www

# Create the main web page
echo 'Hello World' > /var/www/html/index.html

# Define the Nginx server configuration
new_config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;
    location  /404.html {
        internal;
        default_type 'text/html';
        return 404 'Ceci n\'est pas une page';
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}
"

# Create the custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Apply the Nginx server configuration
echo "$new_config" > /etc/nginx/sites-available/default

# Restart Nginx service
if systemctl is-active --quiet nginx; then
    sudo systemctl restart nginx
else
    sudo systemctl start nginx
fi
