#!/usr/bin/env bash

# Install Nginx if not already installed
if ! dpkg -l | grep -q nginx; then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

# Remove default Nginx site configuration
sudo rm -f /etc/nginx/sites-enabled/default

# Create a custom Nginx configuration file
cat <<EOF | sudo tee /etc/nginx/sites-available/custom_header
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By \$host;
        return 200 'Hello, this is web-01!';
    }
}
EOF

# Create a symbolic link to enable the custom configuration
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Test Nginx configuration and reload Nginx
sudo nginx -t
sudo systemctl reload nginx
