#!/usr/bin/env bash
# Configure web-02 to mirror the configuration of web-01
# Add a custom HTTP header named X-Served-By
# Set the value of X-Served-By to the hostname of the server where Nginx is running

# Update package information
sudo apt-get -y update

# Install Nginx web server
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create directories for web content and error pages
sudo mkdir -p /var/www/html /var/www/error

# Set appropriate permissions for the web directories
sudo chmod -R 755 /var/www

# Create a basic HTML page with "Hello World!" content
echo 'Hello World!' > /var/www/html/index.html

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Define the Nginx server configuration
server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"

# Apply the server configuration to the default Nginx site
echo "$server_config" > /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply changes
sudo service nginx restart
