#!/usr/bin/env bash
# Bash script to ping an IP address passed as an argument.

# Check if an argument is provided and display the usage message if not.
[ $# -eq 0 ] && echo "Usage: $0 {IP_ADDRESS}" && exit 1

# Perform the ping 5 times and display the results.
ping -c 5 "$1"
