#!/usr/bin/env bash
#Manages the script manage_my_process.


if [ "${1}" == "start" ]; then
	    "$MANAGE_SCRIPT" &
	        echo "$!" > /var/run/my_process.pid
		    echo "manage_my_process started"
	    elif [ "${1}" == "stop" ]; then
		        if [ -f /var/run/my_process.pid ]; then
				        PID=$(cat /var/run/my_process.pid)
					        kill "$PID"
						        rm /var/run/my_process.pid
							        echo "manage_my_process stopped"
								    else
									            echo "manage_my_process is not running"
										        fi
										elif [ "${1}" == "restart" ]; then
											    if [ -f /var/run/my_process.pid ]; then
												            PID=$(cat /var/run/my_process.pid)
													            kill "$PID"
														            rm /var/run/my_process.pid
															        fi
																    "$MANAGE_SCRIPT" &
																        echo "$!" > /var/run/my_process.pid
																	    echo "manage_my_process restarted"
																    else
																	        echo "Usage: manage_my_process {start|stop|restart}"
fi

