#!/usr/bin/env bash
# This script displays lines containing the "bash" word, allowing you to easily get the PID of your Bash process
# shellcheck disable=SC2009

# Use "ps" command to list all processes, filter the lines containing "bash" and exclude the "grep bash" process
ps aux | grep bash | grep -v "grep bash"
