#!/usr/bin/env bash
# Bash script to check information about the school file

# Check i
if [ -e "school" ]; then
    echo "school file exists"
    if [ -s "school" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if the file is a regular file
    if [ -f "school" ]; then
        echo "school is a regular file"
    else
        echo "(nothing)"
    fi
else
    echo "school file does not exist"
fi
