#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, showing only
# username, user ID, and home directory path for each user

while IFS=":" read -r username uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo "-------------------------"
done < "/etc/passwd"
