#!/usr/bin/env bash

# Use the ssh command to connect to the server 52.3.246.137 with the private key ~/.ssh/school
# Use the -i flag to specify the private key file
ssh -i ~/.ssh/school ubuntu@52.3.246.137
